### ISSUE TITLE
Bug: warn_explicit() argument 3 must be str, not PosixPath

### ISSUE THREAD

**Issue by coler-j** [Pylons/pyramid_openapi3#190] opened 2022-12-01 19:21 UTC
I am getting the following when authentication fails:

```
Traceback (most recent call last):
File "/<path>/pyramid_debugtoolbar/toolbar.py", line 275, in toolbar_tween
    response = _handler(request)
File "/<path>/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
File "/<path>/pyramid_tm/compat.py", line 36, in reraise
    raise value
File "/<path>/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
File "/<path>/pyramid_openapi3/tween.py", line 46, in excview_tween
    warnings.warn_explicit(
TypeError: warn_explicit() argument 3 must be str, not PosixPath
```

Should this be cast to a string? https://github.com/Pylons/pyramid_openapi3/blob/f571800e2d53ea5e23be863100144cd15e87ba84/pyramid_openapi3/tween.py#L60

**Comment by zupo** [comment] 2022-12-01 22:22
Looks like a bug, yes.

Can you please provide a minimal example that shows the failure? It will make it much easier to debug, and then to add a test to make sure it stays fixed.

**Comment by coler-j** [comment] 2022-12-02 13:25
@zupo this issue was caused because during my configuration I am using the path lib library, so I am doing the following:

```
"""
In configuration directory
"""
# The absolute base directory to the `main` project.
BASE_DIR = Path(__file__).resolve().parents[1]

# `OPEN_API_SCHEMA_FILE_LOCATION` is a `PosixPath`
OPEN_API_SCHEMA_FILE_LOCATION = BASE_DIR.joinpath("path/to/openapi.yaml")

"""
in application bootstrap file
"""
config.pyramid_openapi3_spec_directory(OPEN_API_SCHEMA_FILE_LOCATION, route='/api/v1/spec')
```

Instead of your [config example](OPEN_API_SCHEMA_FILE_LOCATION):

```
config.pyramid_openapi3_spec_directory('some/string/only/path/to/openapi.yaml', route='/api/v1/spec')
```

I have worked around this bug for now by doing:

```
config.pyramid_openapi3_spec_directory(str(OPEN_API_SCHEMA_FILE_LOCATION), route='/api/v1/spec')
```

**Comment by zupo** [comment] 2022-12-02 13:58
`filepath` is declared to be a `str` so it is expected that you need to pass a string into `pyramid_openapi3_spec_directory`: https://github.com/Pylons/pyramid_openapi3/blob/5c00ceeb9ec81caf827278ce3c03725f301c2ed5/pyramid_openapi3/__init__.py#L266

I'm closing this as "not a bug". If you are using mypy or similar, that should catch the bug in your code, that is passing a non-string parameter into a function expecting a string.

**Closed by zupo** 2022-12-02 13:58 UTC

**Comment by zupo** [comment] 2022-12-02 14:00
A viable discussion that could take place is whether `filepath` should be converted into a path lib parameter, instead of a str parameter.

But I am definitely against doing sanitation in pyramid_openapi3_spec_directory that is not needed when using proper tooling (such as mypy). Duplication of effort.

**Comment by coler-j** [comment] 2022-12-02 14:15
Yeah, we are not using mypy :(
