### ISSUE TITLE
[Bug] Issue with referencing a schema when using -allOf / -oneOf / -anyOf directives

### ISSUE THREAD

**Issue by 123survesh** [Pylons/pyramid_openapi3#197] opened 2022-12-25 04:22 UTC
Hi,

I recently was trying to reference a schema within a **-allOf** directive and its showing the below error: `pyramid.exceptions.ConfigurationExecutionError: <class 'jsonschema.exceptions.RefResolutionError'>: Unresolvable JSON pointer: 'basicInvoiceDetails'
`

I am saying that this is a bug because, I was able to reference a schema outside of **-allOf** directive and got it working.

**What's working:**
```yaml
orgMetaData:
  type: object
  properties:
    orgname: 
      type: string
    invitestatus: 
      $ref: "#/inviteStatus" # WORKING

inviteStatus:
  type: string
  enum: [true, false, Rejected]

```

**What's not working:**
```yaml
allInvoiceDetails:
  allOf:
    - $ref: "#/basicInvoiceDetails" # NOT WORKING
    - type: object
      properties:
        custname:
          type: string
        invoicetotal:
          type: number

basicInvoiceDetails:
  type: object
  properties:
    invid:
      type: integer
    invoiceno:
      type: string
    invoicedate:
      type: string
      format: date
```

**Comment by zupo** [comment] 2022-12-26 09:37
Can you please make a minimal runnable example that showcases this bug? Something that we can use a test going forward? With dummy values and parameters, not your project specific names.

**Comment by zupo** [comment] 2024-03-07 21:04
There was no reply, so I'm closing this. If the issue is still there, please let me know and I'll re-open.

**Closed by zupo** 2024-03-07 21:04 UTC
